version: '3.8'

services:
  notificador-api:
    build: .
    container_name: notificador_server
    restart: always
    ports:
      - "5050:5050"
    env_file:
      - .env
    # Si quieres persistir logs fuera del contenedor
    volumes:
      - ./logs:/app/logs
